### ISSUE TITLE
Ctrl+c does not exit insert mode

### ISSUE THREAD

**Issue by bdd4329** [prompt-toolkit/pyvim#124]
My workflow involves using Ctrl+c to exit insert mode since it requires less movement than using Esc. Please add/fix support for exiting insert mode via Ctrl+c.

**Comment by lieryan** [comment]
This is fairly simple to add into your .pyvimrc:

```
from prompt_toolkit.filters import ViInsertMode
from prompt_toolkit.key_binding.vi_state import InputMode

__all__ = (
    'configure',
)

def configure(editor):
    @editor.add_key_binding('c-c', filter=ViInsertMode())
    def _(event):
        editor.application.vi_state.input_mode = InputMode.NAVIGATION
```

Note that using [C-c does not behave the same as Esc in vim](https://stackoverflow.com/questions/5030164/whats-the-difference-between-ctrlc-and-ctrl); C-c is force switching to insert mode, not regular switch to normal mode. Using C-c to quit insert mode is generally a bad habit. Try using C-[ instead if your Esc key is hard to use, or try remapping keys like `Caps Lock` or `jj`.

**Comment by bdd4329** [comment]
Thanks, this works perfectly. Also, thanks for pointing out the difference in Ctrl+c vs Ctrl+[. I always found Ctrl+c faster to type, and I don't normally use vim plugins so this doesn't usually effect me. However, it is good to know.
